### ISSUE TITLE
Provide for an introduction of GOB

### ISSUE THREAD

**Issue by Vegter** [Amsterdam/GOB#1]
The description is a high-level overview of what the project is for, what it does and in what way it should be used. The description can double as a mission to keep you focussed and on track, so it is wise to define this as early in the process as possible.

Be sure to answer these questions in your description:

    What is this project?
    How does it work?
    Who are the users?
    What is the benefit for the users?
    What is the goal of this project?

Start with the most important things so people can continue their search if this project is not what they are looking for.

Make this section shine: If your project has a front-end include a screenshot here; if there is a demo or there are live examples, include links; if there are features, list them.

**Comment by dolhuis** [comment]
Because this is our main entry and communication point for this project we should also have a Dutch section. Is laagdrempelig, zeg maar.

**Comment by dolhuis** [comment]
Hmmm. I see the whole of https://amsterdam.github.io/ is also English. So maybe drop the requirement of making this project bi-lingual? An defer it to another issue?

**Comment by Vegter** [comment]
I thought to start with a short Dutch introduction for GOB, then add an english introduction. The main goal is "to get people on the train" and Ducth communities will easier find a Dutch intro than an English intro. All the rest I will keep English.

**Comment by bvhme** [comment]
My idea about this is that anyone who decides on the ability to implement
this software in their own context will to some level be able to read
English. By adding bilingual content the risk of confusions and building a
new vocabulary are high. I would recommend using one language in the
development environment and leave the 'marketing' to business people in
other orgs out of these repo's.

In NLX we have a seperate marketing site for the Dutch speaking audienc
<https://nlx.io/>e, while the docs <https://docs.nlx.io/> and code are in
English.

**Comment by Vegter** [comment]
Agree, the README of GOB is for now the only Dutch document so it can be considered (and is) only to attire other Dutch governments to find our project.
OK, let's have the English README as a start and discard the Dutch one. OK? Or shall I leave the Dutch one as README.nl.md and make a reference to it in the English version. @dolhuis @bvhme

**Comment by Vegter** [comment]
BTW Haarlem (with help of Dictu) is publishing readme in Dutch
https://github.com/Haarlem/zaakregistratiecomponent

**Comment by bvhme** [comment]
For Haarlem it differs per project, where they are bound to Dutch standards
(like the ones set by KING, RSGBz etc) they use Dutch, however in more
general purpose projects they use English like in `digitale-weaardepapieren`
<https://github.com/Haarlem/digitale-waardepapieren>. This is explicitly to
not have to mix languages.

My suggestion would be to have the README.nl.md file in there for now but
consider it 'to be deprecated', and move to English step by step.

**Comment by Vegter** [comment]
I have made the English README the leading README. The Dutch version is marked as being of limited use.
